lecture1-accordion
js-tasks-ru/htmlcss-20230530_nazarov-ivan-1992 pull request #3
Opened 2023-06-20 20:33 UTC by ivan712

2023-06-21 15:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-21 15:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-21 15:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-21 15:18 UTC, GSemikozov requested changes

2023-06-21 15:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
лишнее ограничение

2023-07-19 06:57 UTC, ivan712 commented
Всё исправил в последнем коммите

2023-07-19 21:21 UTC, GSemikozov approved these changes

2023-07-19 21:21 UTC, merged